const LISTMOVIE = {
  LOADING: 'LISTMOVIE_LOADING',
  FETCH_SUCCESS: 'LISTMOVIE_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTMOVIE_FETCH_FAILED',
};

const MOVIEDETAIL = {
  LOADING: 'MOVIEDETAIL_LOADING',
  FETCH_DETAIL_SUCCESS: 'MOVIEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'MOVIEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_ADD_MOVIE: 'MOVIEDETAIL_FETCH_ADD_MOVIE'
}

const MYMOVIE = {
  FETCH_SUCCESS: 'MYMOVIE_FETCH_SUCCESS',
  REMOVE_MOVIE: 'MYMOVIE_REMOVE_MOVIE'
}

export { LISTMOVIE, MOVIEDETAIL, MYMOVIE };
